### ISSUE TITLE
Text labels in drawing area

### ISSUE THREAD

**Issue by ericsuh** [fariapp/fari-app#130]
## 🚩 Is your feature request related to a problem? Please describe

I would like to be able to indicate what certain parts of the drawing are in the drawing area

## ✅ Describe the solution you'd like

The ability to add movable, re-editable text would be great so that I can add things like names for different zones and character tokens

## ✏️ Describe alternatives you've considered

Drawing text on the map freehand, which is awkward and difficult

**Comment by RPDeshaies** [comment]
That's a nice suggestion. I'll think about it. Thanks!
