### ISSUE TITLE
Vehicle/Companion Sheets

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari-app#134]
## 🚩 Is your feature request related to a problem? Please describe

Currently no options exist for companions, vehicles, familiars etc, that require a full (custom) sheet AND are player-controlled.
Players cannot be in same tab with two sheets under their control.

## ✅ Describe the solution you'd like

Allow players to claim control of a companion/vehicle sheet etc.

**Comment by RPDeshaies** [comment]
As a workaround for now, I would suggest adding multiple custom fields on a player's character sheet but I understand it's less than ideal. Will think about it

**Comment by RPDeshaies** [comment]
Will be done within https://github.com/fariapp/fari/issues/167
