### ISSUE TITLE
Tachyon Squadron Ship/Character template

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari-app#142]
## 🚩 Is your feature request related to a problem? Please describe

* No character sheet template exists for Tachyon Squadron Ships (which have their own unique template).
* Tachyon Squadron player character sheets can be almost created by modifying custom sheet, except for grouping of skills. (= Not a really big issue)

## ✅ Describe the solution you'd like

* A Tachyon Squadron ship sheet template added to character sheet templates
* A Tachyon Squadron character sheet template added to character sheet templates [to complete support for Tachyon squadron]
(More then willing to help out!)

**Comment by RPDeshaies** [comment]
I never played Tachyon Squadron so help would be very appreciated.

I'll try to do this and Fate of Cthulhu as official templates and ask for a review by you once I have a working version of Tachyon Squadron if that's ok with you ?

Will be done within https://github.com/fariapp/fari/issues/167

**Comment by SpaceDiceMan** [comment]
Of course!

**Comment by RPDeshaies** [comment]
Someone in the community made Tachyon Squadron templates available inside fari!

![image](https://user-images.githubusercontent.com/6224111/129374771-70f6ddfd-43ca-4f2d-adb7-d9efce8f8945.png)
