### ISSUE TITLE
Add additional "Sort" options to the index card container

### ISSUE THREAD

**Issue by jmicu** [fariapp/fari-app#246]
## 🚩 Is your feature request related to a problem? Please describe
My Fate Core scenes typically last multiple sessions each. Cards of all types (Aspects, NPCs, etc) accumulate quickly, and that becomes difficult to manage.

I become frustrated when I know which card I need to refer to / edit, but can't find it. 

The existing sort option helps me find flagged vs unflagged; the upcoming "drag'n'drop" feature will let me customize the card layout, but doing that card-by-card for a huge scene would be tedious and time-consuming.

## ✅ Describe the solution you'd like
If "Sort" included additional options, I could manage my session's cards much more efficiently. Options could include any of:
- sort by color
- sort alphabetically
- sort by creation datetime
- sort by last-edited datetime
- sort by type ("Aspect", "NPC", "Boost", index card, etc)
- sort by user custom (this option would remember every card's position the last time I dragged'n'dropped something)

Additionally: if, once a Sort option was selected, cards that were altered somehow _immediately_ re-sorted as needed, that would be incredible! E.g. if sorting by color, and a red card changed to green, if it then moved to join its green buddies. 💯 bonus points.

## ✏️ Describe alternatives you've considered
I run two tables currently. I could manually drag'n'drop everything to where I need it for our most current scene (for each campaign), and then stay organized from there. The drawback here is the same, albeit lessened. The play loses momentum every second I spend moving this card here, that card there.

Or, I could simplify the card container by moving more cards into the Private section when not in immediate use. The drawback here is that the players can't see e.g. what all their invokable / compellable options are; they have to recall the one they want, then ask me to move it back to Public tab again.

Another feature that helped me find specific cards quickly was the expansion from three columns, to four. I would _gladly_ use 5, 6, or even 7 columns if I could. (For my Fari games, I use two 27" 4K monitors, plus a high-end tablet and sometimes a laptop as well.)

## 📄 Additional context
Card management is currently my greatest challenge with Fari. This is partly because I use it as both scene-planner _and_ historical record; each session, when finished, gets cloned and renamed to the next session. This way I can look back through past sessions and see what happened, without having to maintain one huge notes file that records all events.

Being able to quickly organize old sessions would also help tremendously, since I could glance over an old session and immediately find things that could be relevant in future sessions.

I realize Fari isn't intended as a complete manage-all-content-for-all-your-campaigns app, but I would like to use it that way anyway!  :)  I'll take anything that helps me accomplish that.

**Comment by RPDeshaies** [comment]
Released with v5. With the latest implementation, do you still think we need sort options by color, alphabetical and things like that ?

**Comment by RPDeshaies** [comment]
Closing this since V5 released new sorting options :)
