### ISSUE TITLE
Background import

### ISSUE THREAD

**Issue by SpaceDiceMan** [fariapp/fari-app#251]
## 🚩 Is your feature request related to a problem? Please describe

Currently the freehand drawing tool does not allow import of existing images. If pre-existing images were possible, pre-made zones or tactical situations (eg Tachyon Squadron Maneuver Sheet) could be uploaded and used with tokens.

## ✅ Describe the solution you'd like

Allow upload (and scaling) of existing pngs as background for the free-draw area.

**Comment by RPDeshaies** [comment]
SImilar to #250

**Comment by RPDeshaies** [comment]
Commented here https://github.com/fariapp/fari/issues/250#issuecomment-812153256

**Comment by RPDeshaies** [comment]
Will track this on Canny! https://fari.canny.io/feature-requests/p/custom-themesbackgrounds
