### ISSUE TITLE
Fari Polish Localization and an inconsistancy on the Fari Wiki

### ISSUE THREAD

**Issue by RenaGone** [fariapp/fari-app#318]
## 🚩 Is your feature request related to a problem? Please describe

Lack of Polish localization in the Fari app.
Also, I wanted to translate the about page like it's said in the "Internationalization and localization" article on the wiki (https://fari.app/fari-wiki/internationalization-and-localization), but the links are broken :v (https://github.com/fariapp/fari/tree/master/lib/routes/About/page , https://raw.githubusercontent.com/fariapp/fari/master/lib/routes/About/page/About.en.md )
Tbh I dont even know if there even is an about page on the site rn.
In any case there is some sort of an inconsistancy here.

## ✅ Describe the solution you'd like

Usage of the localization and character sheet templates I provided on the discord server :p
[Fari Polish Localization.txt](https://github.com/fariapp/fari/files/6808518/Fari.Polish.Localization.txt)

**Comment by RPDeshaies** [comment]
You are totally right! I'll remove the links to the about page because it was removed a couple of weeks ago.

I'll upload the polish translations! Thank you so much for this!

**Comment by RPDeshaies** [comment]
Translations uploaded. Will be part of v5.1

🥳 🥳 🥳
