### ISSUE TITLE
Can't modify own Slot Tracker bubbles from Characters tab

### ISSUE THREAD

**Issue by hawkerm** [fariapp/fari-app#362]
## 🚩 Describe the bug

Related to #361

Can't modify my own Slot Tracker bubbles on Character sheet tab, need to open full character sheet to edit. Would be nice for them to work like point counters and be modifiable in main character page.

## 🔢 Steps to reproduce

1. Add a Slot Tracker to character sheet
2. Click on Character Tab
3. Try and click on a bubble to fill it, can't...

## 🟢 Expected behavior

Would expect to be able to modify my own slot tracker without opening full character sheet.

## 🔴 Actual behavior

Need to open character sheet to manipulate.

## 💅 Screenshots

![image](https://user-images.githubusercontent.com/8959496/151731706-0c5771ea-1839-4da7-a80b-ce95df99a70c.png)

Compared to point counters which are modifiable:

![image](https://user-images.githubusercontent.com/8959496/151731728-f6f836ed-34df-489d-83ca-4f2b213577f4.png)

## 🖥 Desktop or Smartphone

- OS: Windows
- Browser: Edge
- Device: PC

**Comment by RPDeshaies** [comment]
I actually want to enable more than one block types to be editable in the character cards!

Will be tracked here: https://fari.canny.io/feature-requests/p/make-slot-tracker-blocks-editable-in-card-view

**Comment by hawkerm** [comment]
Oh, didn't realize there was a whole other feature tracker. Is there a reason you're using that over projects here on GitHub to keep it all in one place?
