### ISSUE TITLE
Wide screen monitors can't display more than 4 characters in a row

### ISSUE THREAD

**Issue by hawkerm** [fariapp/fari-app#364]
## 🚩 Describe the bug

If have a wider display, the display has white space on left/right instead of allowing for more columns within the rows for the character page and index cards in scenes.

## 🔢 Steps to reproduce

1. Open page on a wider monitor or expand window across two screens.
2. See white space of page gutters on left/right

## 🟢 Expected behavior

Layout adapts or available space to show more columns.

## 🔴 Actual behavior

Fixed number of columns regardless of display width.

## 💅 Screenshots

![image](https://user-images.githubusercontent.com/8959496/151743105-0a639050-8e5e-4df6-9be7-18c52615f803.png)

## 🖥 Desktop or Smartphone

- OS: Windows
- Browser: Edge
- Device: PC

## 📄 Additional context

Related to #144

**Comment by RPDeshaies** [comment]
This is actually not a bug since the page as a max width by design!

**Comment by hawkerm** [comment]
It's a usability bug in the original design then... just because it was done intentionally originally doesn't mean that it's supposed to be the right choice for the user.

**Comment by RPDeshaies** [comment]
Hey! So I made an horizontal scrollbar for character cards, and #382 is going to enable support for more index cards on the X axis so stay tuned for this!
