### ISSUE TITLE
Broken link incorrectly prepending https://fari.app

### ISSUE THREAD

**Issue by jamestingedwards** [fariapp/fari-app#373]
## 🚩 Describe the bug

On the Fari homepage, the link to "Fari Games" resolves to "page not found" because the URL is https://fari.app/https:/fari.games instead of https://fari.games

## 🔢 Steps to reproduce

1. Go to https://fari.app
2. Scroll down
3. Click on the link to "FARI GAMES"
5. See 'Page not found' and incorrect URL

## 🟢 Expected behavior

Link resolves to https://fari.games

## 🔴 Actual behavior

Link resolves to https://fari.app/https://fari.games

## 🖥 Desktop or Smartphone

- OS: MacOS
- Browser: Chrome
- Device: MacBook Air

![image](https://user-images.githubusercontent.com/5006128/159836523-357d3d55-93cc-456d-9a36-665e8fb88942.png)

**Comment by RPDeshaies** [comment]
Oh you are totally right. I'll take a look ASAP! Sorry for the delay, I hadnt seen the notification.

**Comment by jamestingedwards** [comment]
Working beautifully now thanks (and thanks for all the lovely work on Fari!)
