### ISSUE TITLE
dragging notes into a bad guy's card causes a crash

### ISSUE THREAD

**Issue by Froozigiusz** [fariapp/fari-app#407]
## 🚩 Describe the bug

When I try to put some boost or an item into a subsection of a bad guy entire application crashes and needs restarting 

## 🔢 Steps to reproduce

1. Go to 'SCENES'
3. Create a 'BAD GUY' card from the 'FATE' collection
4. Click 'Add Sub Card'
5. Create a 'BOOST' or any other card
6. Move 'BOOST' card near the initial 'INDEX CARD' by dragging it with 'Move' icon (not 'Move to' function!)

## 🟢 Expected behavior

It should work the same as a 'Move to' mechanic – that is moving notes in and out of subsections just by dragging note around with a cursor.

## 🔴 Actual behavior

'Move' icon only allows to reorder notes, but only inside it's own folder/box and not between them.

## 🖥 Desktop or Smartphone

- OS: Ubuntu 20.04.4 LTS x86_64
- Browser: Brave
- Device: PC

## 📄 Additional context

As I was testing this bug for documentation I also found a problem with 'Move to' command. It cannot move the card into the main scene folder( / ), only between 'BAD GUY's'  folders for example.

This problem was also brought up here, although it relies on this issue to convey any information: https://fari.canny.io/bugs/p/dragging-notes-into-a-bad-guys-card-causes-a-crash

**Comment by RPDeshaies** [comment]
Thanks for this, I've opened a pull request which I'll merge very soon. Also, thanks for such a thorough "Steps to reproduce" section, it really helped me figure out what was hapenning!
