### ISSUE TITLE
Unreliability of 'Move To' function makes it almost compeletly unusable

### ISSUE THREAD

**Issue by Froozigiusz** [fariapp/fari-app#410]
## 🚩 Describe the bug

There are many small problems that lead to my complaint, but in essence they are:
 - unable to 'Move Out' some cards in some levels of card folders.
 - not moving card to selected location if the card is in more than one depth of card folders.
 - not being able to move entire card folders between cards.
 - sometimes program says it can move something but then it just doesn't.

## 🔢 Steps to reproduce

As this "bug report" consists of multiple smaller bugs, I am unable to properly make a step by step section of this complaint. Just try to recreate my structure of cards as seen in 'Screenshots' section and see for yourself what moves and what not (like actually moves, not that it just says it can).

## 🟢 Expected behavior

 - able to 'Move Out' every single card, even if by a single step.
 - can only pack a card into another folder only if they are on the same level ('Mayor's property' should only have option to 'Move Out', and 'hates cats' to either 'Move Out' or go into 'golden collar' or precious coin').
 - ⬆ this folder philosophy may not be the intended one, but at least is consistent. Maybe to this way of foldering also add one additional layer of folder cards from below, then it will be able to move cards by one command and not two.
 - being able to move card folders with content still inside (unless it is pinned)

## 🔴 Actual behavior

…

I think I've made my complaints clear enough. All I will say here is one word: "inconsistency".

## 💅 Screenshots

Examples of missing (in my opinion) options for moving cards

![Zrzut ekranu z 2022-06-30 11-00-10](https://user-images.githubusercontent.com/77325322/176637522-157e796b-8a4a-46fd-a225-314ae3ed7ca0.png)

![Zrzut ekranu z 2022-06-30 11-01-07](https://user-images.githubusercontent.com/77325322/176637549-d7f24e6e-7078-4c71-b784-d213022fccd2.png)

(side note; making long and complicated folders can look bad, maybe tweak some visual formatting?)

## 🖥 Desktop or Smartphone

- OS: Ubuntu 20.04.4 LTS x86_64
- Browser: Brave
- Device: PC

## 📄 Additional context

I was mentioning this problem in the #407 , but seeing as 'Move' function was not changed to be interchangable with 'Move To', probably there is a design decision behind that, and I can respect that. But that means, that both of them need to work correctly and as intended, thus I made another bug report.

**Comment by lynn0702** [comment]
I've researched this and found the root cause resulting in PR submission. 

At this time only single level nesting is supported.  Multi level nesting was erroneously possible because of the bug itself.

**Comment by lynn0702** [comment]
https://github.com/fariapp/fari-app/pull/429
